version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn install
    preBuild:
      commands:
        - yarn build
    build:
      commands:
        - cd dist && yarn install --production
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
