version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn build
  build:
    commands:
      - echo "⚙️ installing build project"
      - cd dist && yarn install --production
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  post_build:
    commands:
    - echo "✅ Post build successful"
