version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "⚙️ started install"
      - yarn install
  pre_build:
    commands:
      - yarn build
  build:
    commands:
      - echo "⚙️ installing build project"
      - cd dist && yarn install --production
  post_build:
    commands:
    - echo "✅ Post build successful"
artifacts:
  baseDirectory: dist
  files:
    - '**/*'
