version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "⚙️ started install"
      - yarn install
  pre_build:
    commands:
      - yarn add typescript
      - yarn add @adonisjs/assembler --save-dev
      - yarn build
  build:
    baseDirectory: build
    commands:
      - echo "⚙️ installing build project"
      - yarn install --production
  post_build:
    commands:
    - echo "✅ Post build successful"
artifacts:
  baseDirectory: build
  files:
    - '**/*'
